version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "./config:/etc/nginx/config"
      - "./projects:/etc/nginx/projects"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/volumes:/volumes"
    ports:
      - "80:80"
      - "443:443"
    restart: always
   